from .typeAInstruction import TypeAInstruction
from .typeBInstruction import TypeBInstruction
from .typeCInstruction import TypeCInstruction
from .typeDInstruction import TypeDInstruction
from .typeEInstruction import TypeEInstruction
from .typeFInstruction import TypeFInstruction
from .typeGInstruction import TypeGInstruction
from .typeIInstruction import TypeIInstruction
from .typeJInstruction import TypeJInstruction
from .typeKInstruction import TypeKInstruction
